on:
  - push
  - pull_request

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Set env ccxname
        run: echo "ccxname=$(ls dist/*.ccx -1 | awk 'NR==1' | awk -F'/' '{print $2}')" >> $GITHUB_ENV

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ccxname }}
          path: dist/${{ env.ccxname }}
